version: "3.9"

services:

  database:
    container_name: database
    image: mysql:8.0.33
    restart: always
    env_file:
      - .env  # Use the .env file for environment variables
    environment:
      MYSQL_DATABASE: springsecurity
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_PORT: 3307
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - springsecurityNetwork

  springsecurity:
    image: 'springsecurity:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springsecurity
    restart: on-failure
    env_file:
      - .env  # Use the .env file for environment variables
    ports:
      - "1223:1223"
    environment:
      - server.port=1223
      - spring.datasource.username=${DATABASE_USERNAME}
      - spring.datasource.password=${DATABASE_PASSWORD}
      - SECURITY_DB_IP=database
      - SECURITY_DB_PORT=3307
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3307/springsecurity
    depends_on:
      - database
    networks:
      - springsecurityNetwork

networks:
  springsecurityNetwork: